// snaxopedia-ui/src/components/LeftPage.vue
<template>
  <div class="left-page">
    <header class="header"><span class="title">Snaxopedia</span></header>
    <div class="locations-list">
      <div
        class="group"
        v-for="group in bugsGroupedByLocation"
        :key="group.location"
      >
        <h2 class="group-title">
          <img
            :src="locationURL(group.location)"
            :alt="group.location"
            :title="group.location"
            class="location-image"
          />
          <span>{{ group.location }}</span>
        </h2>
        <ul class="group-bugs">
          <li
            v-for="bug in group.bugs"
            :key="bug.name"
            :class="[
              'bug',
              { 'has-photo': bug.hasBeenPhotographed },
              { 'is-selected': bug.isSelected },
            ]"
            @click="setSelectedBug(bug)"
          >
            <img
              :src="bugImageURL(bug.name)"
              :alt="bug.name"
              :title="bug.name"
              class="bug-image"
            />
            <span
              v-if="bug.hasBeenSeen"
              class="has-been-seen on material-symbols-outlined"
              @click.stop="
                changeBugStatus(bug, {
                  hasBeenSeen: false,
                  hasBeenPhotographed: false,
                })
              "
              >visibility</span
            >
            <span
              v-else
              class="has-been-seen off material-symbols-outlined"
              @click.stop="changeBugStatus(bug, { hasBeenSeen: true })"
              >visibility_off</span
            >

            <span
              v-if="bug.hasBeenPhotographed"
              class="has-been-photographed on material-symbols-outlined"
              @click.stop="changeBugStatus(bug, { hasBeenPhotographed: false })"
              >check_circle</span
            >
            <span
              v-else
              class="has-been-photographed off material-symbols-outlined"
              @click.stop="
                changeBugStatus(bug, {
                  hasBeenSeen: true,
                  hasBeenPhotographed: true,
                })
              "
            >
              circle</span
            >
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { storeToRefs } from "pinia";
import { useStore } from "../stores/store";
import { Bug } from "../types";

const store = useStore();
const { setSelectedBug, modifyBug } = store;
const { getBugsGroupedByLocation: bugsGroupedByLocation } = storeToRefs(store);

const locationURL = (locationName: string) =>
  `http://localhost:8000/locations/${locationName}.webp`;
const bugImageURL = (bugName: string) =>
  `http://localhost:8000/bugs/${bugName}.png`;

const changeBugStatus = (
  bug: Bug,
  data: {
    hasBeenSeen?: boolean;
    hasBeenPhotographed?: boolean;
    isSelected?: boolean;
  }
) => {
  modifyBug(bug, data);
};
</script>

<style scoped>
.left-page {
  height: 100%;
  width: 50vw;
}

.header {
  display: flex;
  justify-content: center;
  align-items: center;
  align-content: center;

  background-color: var(--accent-blue);
  height: 5rem;
  width: 100%;
}

.header .title {
  color: var(--font-color);
  font-size: 2.5rem;
}

.locations-list {
  height: calc(100% - 5rem);
  width: 100%;
  overflow-y: auto;
}

.group-title {
  display: flex;
  justify-content: center;
  align-items: center;
  align-content: center;
  flex-wrap: nowrap;
}

.group-title .location-image {
  transform: rotate(-15deg);
  width: 10rem;
}

.group-title span {
  position: relative;
  color: var(--location-font-color);
  text-shadow: 2px 2px var(--text-shadow);
  font-size: 3rem;
  -webkit-text-stroke-width: 1px;
  -webkit-text-stroke-color: var(--font-color);
  -webkit-text-fill-color: var(--location-font-color);
}

.group-bugs {
  list-style: none;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;

  margin: 0;
  padding: 0;
}

.group-bugs .bug {
  background-color: var(--no-photo-bug);
  margin: 0.3rem;
  border-radius: 1rem;
  position: relative;
}

.group-bugs .bug .bug-image {
  width: 9rem;
}

.group-bugs .bug .has-been-seen,
.group-bugs .bug .has-been-photographed {
  position: absolute;
  bottom: -0.2rem;
  background-color: var(--font-color);
  border-radius: 1rem;
  font-size: 2rem;
  cursor: pointer;
}

.group-bugs .bug .has-been-seen {
  left: -0.2rem;
}

.group-bugs .bug .has-been-photographed {
  right: -0.2rem;
}

.group-bugs .bug .has-been-seen.off,
.group-bugs .bug .has-been-photographed.off {
  color: var(--icon-color);
}

.group-bugs .bug .has-been-seen.on,
.group-bugs .bug .has-been-photographed.on {
  color: var(--seen-green);
}

.group-bugs .bug .has-been-seen.off:hover,
.group-bugs .bug .has-been-photographed.off:hover {
  color: var(--seen-green);
}

.group-bugs .bug.has-photo {
  background-color: var(--has-photo-bug);
}

.group-bugs .bug:hover,
.group-bugs .bug.is-selected {
  background-color: var(--accent-blue);
  border: 0.3rem solid var(--font-color);
  margin: 0rem;
  border-radius: 1rem;
}
</style>

// snaxopedia-react/src/components/LeftPage/LeftPage.tsx
import type { Bug as BugType } from "../../types"
import "./LeftPage.css"

const locationURL = (locationName: string) => `http://localhost:8000/locations/${locationName}.webp`
const bugImageURL = (bugName: string) => `http://localhost:8000/bugs/${bugName}.png`

function Bug(props: any) {
  const { bug, modifyBug, setSelectedBug }: { bug: BugType, modifyBug: Function, setSelectedBug: Function } = props
  const { hasBeenPhotographed, hasBeenSeen, isSelected } = bug

  const bugClasses = `bug${hasBeenPhotographed ? ' has-photo' : ''}${isSelected ? ' is-selected' : ''}`;

  const changeBugStateEvent = (data: { hasBeenSeen?: boolean, hasBeenPhotographed?: boolean, isSelected?: boolean, }) => (evt: any) => {
    evt.stopPropagation()
    modifyBug(bug, data)
  }

  return (<li className={bugClasses} onClick={() => setSelectedBug(bug)}>
    <img className="bug-image" src={bugImageURL(bug.name)} alt={bug.name} title={bug.name} />
    {hasBeenSeen ?
      (<span className="has-been-seen on material-symbols-outlined" onClick={changeBugStateEvent({ hasBeenSeen: false, hasBeenPhotographed: false })}>visibility</span>) :
      (<span className="has-been-seen off material-symbols-outlined" onClick={changeBugStateEvent({ hasBeenSeen: true })}>visibility_off</span>)
    }
    {hasBeenPhotographed ?
      (<span className="has-been-photographed on material-symbols-outlined" onClick={changeBugStateEvent({ hasBeenPhotographed: false })}>check_circle</span>) :
      (<span className="has-been-photographed off material-symbols-outlined" onClick={changeBugStateEvent({ hasBeenSeen: true, hasBeenPhotographed: true })}>circle</span>)
    }
  </li>)
}

function Location(props: any) {
  const { group, modifyBug, setSelectedBug }: { group: { location: string, bugs: BugType[] }, modifyBug: Function, setSelectedBug: Function } = props

  return (<div className="group">
    <h2 className="group-title">
      <img className="location-image" src={locationURL(group.location)} alt={group.location} title={group.location} />
      <span>{group.location}</span>
    </h2>
    <ul className="group-bugs">
      {group.bugs.map((bug: BugType) => <Bug key={bug.name} bug={bug} modifyBug={modifyBug} setSelectedBug={setSelectedBug} />)}
    </ul>
  </div>)
}

export default function LeftPage(props: any) {
  const { snaxopedia, modifyBug, setSelectedBug }: { snaxopedia: BugType[], modifyBug: Function, setSelectedBug: Function } = props

  return (<div className="left-page">
    <header className="left-header"><span className="title">Snaxopedia</span></header>
    <div className="locations-list">
      {snaxopedia.map((group: any) => <Location key={group.location} group={group} modifyBug={modifyBug} setSelectedBug={setSelectedBug} />)}
    </div>
  </div>)
}
