// snaxopedia-vue/src/App.vue
<template>
  <LeftPage />
  <RightPage />
  <Loading v-if="loading" />
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import { storeToRefs } from "pinia";
import { useStore } from "./stores/store";

import LeftPage from "./components/LeftPage.vue";
import RightPage from "./components/RightPage.vue";
import Loading from "./components/Loading.vue";

const store = useStore();
const { loadSnaxopedia } = store;
const { loading } = storeToRefs(store);

onMounted(() => loadSnaxopedia());
</script>

<style scoped></style>

// snaxopedia-solid/src/App.tsx
import { Component, onMount } from 'solid-js'
import type { StoreContext } from '../types'
import LeftPage from './components/LeftPage/LeftPage'
import Loading from './components/Loading/Loading'
import RightPage from './components/RightPage/RightPage'
import { useStore } from './stores/store'

const App: Component = () => {
  const [state, { loadSnaxopedia }]: StoreContext = useStore()
  onMount(() => { loadSnaxopedia() })

  return (<>
    <LeftPage />
    <RightPage />
    {state.loading && <Loading />}
  </>)
}

export default App
